name: Build Zikula module
description: Build and test a Zikula module
inputs:
  vendor_name:
    description: Vendor name
    required: true
  module_name:
    description: Module name
    required: true
  module_version:
    description: Module version
    required: true
  core_version:
    description: Core version
    required: true
  base_dir:
    description: Path to the directory containing the extensions folder (including trailing slash)
    required: false
  create_artifacts:
    description: Create artifacts
    required: false
    default: false
  database_host:
    description: Database host
    required: false
    default: mysql
  database_port:
    description: Database port
    required: false
    default: 3306
  database_user:
    description: Database user
    required: false
    default: zikula
  database_pass:
    description: Database password
    required: false
    default: zikula
  database_name:
    description: Database name
    required: false
    default: zikula
  tools:
    description: Comma-separated list of desired analysis tools
    required: false
    default: ',phplint,parallel-lint,lint:container,lint:yaml,lint:twig,translations,doctrine-info,phpcs,phpunit-bridge,security-checker,phploc,phpmetrics,php-coupling-detector,deprecation-detector,'
runs:
  using: docker
  image: docker://guite/zikula-action
branding:
  icon: check
  color: orange
