name: Build Zikula module
description: Build and test a Zikula module
inputs:
  vendor_name:
    description: Vendor name
    required: true
    default: Acme
  module_name:
    description: Module name
    required: true
    default: News
  module_version:
    description: Module version
    required: true
    default: '1.0.0'
  core_version:
    description: Core version
    required: true
    default: ZK20
  base_dir:
    description: Path to the directory containing the modules folder (including trailing slash)
    required: false
  database_host:
    description: Database host
    required: false
    default: mysql
  database_port:
    description: Database port
    required: false
    default: 3306
  database_user:
    description: Database user
    required: false
    default: zikula
  database_pass:
    description: Database password
    required: false
    default: zikula
  database_name:
    description: Database name
    required: false
    default: zikula
  tools:
    description: Comma-separated list of desired analysis tools
    required: false
    default: ',phplint,parallel-lint,lint:container,lint:yaml,lint:twig,phpcs,php-cs-fixer,phpunit-bridge,psecio-parse,security-checker,churn,phploc,phpmetrics,php-coupling-detector,deprecation-detector,'
  create_artifacts:
    description: Create artifacts
    required: false
    default: false
outputs:
  tar_archive:
    description: File name of module archive in tar.gz format which can be used for a release
  zip_archive:
    description: File name of module archive in zip format which can be used for a release
runs:
  using: docker
  image: Dockerfile
branding:
  icon: check
  color: orange
