name: 'Build module'
description: 'Build and test a Zikula module'
inputs:
  vendor-name:
    description: 'Vendor name'
    required: true
    default: 'Acme'
  module-name:
    description: 'Module name'
    required: true
    default: 'News'
  module-version:
    description: 'Module version'
    required: true
    default: '1.0.0'
  core-version:
    description: 'Core version'
    required: true
    default: 'ZK20'
  create-artifacts:
    description: 'Create artifacts'
    required: false
    default: false
outputs:
  result:
    description: 'Module artifacts which can be used for a release'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.vendor-name }}
    - ${{ inputs.module-name }}
    - ${{ inputs.module-version }}
    - ${{ inputs.core-version }}
    - ${{ inputs.create-artifacts }}
branding:
  icon: 'check'
  color: 'orange'
